name: jupyter-react
channels:
  - conda-forge
#  - defaults
dependencies:
  - jupyter-packaging
  - matplotlib
  - nodejs=18.7.0
  - pandas
  - pip
  - pycurl
  - pytest
  - python=3.10.4
  - twine
  - yarn=1.22.19
  - pip:
    - jupyterlab==4.0.0a27
    - ipywidgets==8.0.1
#    - jupyterlab-lsp
#    - python-language-server[all]
    - plotly
    - bqplot
    - pyecharts
